# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs unit tests for Mock"
  lane :testMock do
    gradle(task: "testMockDebugUnitTest")
  end

  desc "Runs instrumented tests for Mock"
  lane :instrumentedTestMock do
    list_devices
    gradle(task: "connectedMockDebugAndroidTest")
  end

  desc "Builds for Mock Debug"
  lane :assembleMockDebug do
    gradle(task: "assembleMockDebug")
  end

  desc "Builds for Prod Release"
  lane :assembleProdRelease do
    gradle(task: "assembleProdRelease")
  end

  desc "Clean"
  lane :clean do
    gradle(task: "clean")
  end

  # desc "Deploy a new version to the Google Play"
  # lane :deploy do
  #   gradle(task: "clean assembleRelease")
  #   upload_to_play_store
  # end

  lane :list_devices do
    adb_devices.each do |device|

    version = adb(command: "shell getprop ro.build.version.release").strip

    api_level = adb(command: "shell getprop ro.build.version.sdk").strip
    
    model = adb(command: "shell getprop ro.product.model").strip
      
    serial = (device.serial).strip
  
    puts "Model #{model} , Serial Number #{serial}, Version #{version}, API Level #{api_level} is connected"
    end
  end

end
